#!/bin/bash
x=$(pwd);

rev=$1;
if [ ! -d "$x/.hg" ] ; then
    while [ "$x" != "/" ] ;
        do x=$(dirname "$x");
        test -e "$x/.hg" && break;
    done
fi

if [ "$x" = "/" ] ; then
    echo "No mercurial repository found." 1>&2;
    exit
fi


cd "$x" || exit
url=$(awk -F "=" '/default/ {print $2}' .hg/hgrc|sed -e "s/\ //g;")

if [[ "$0" == *"hg-url"* ]] ; then
    echo "$url";
    exit;
fi

if [ "$rev" = "" ] ; then
    rev=$(hg tip | grep changeset | cut -d: -f3);
fi
if [ "$rev" != "" ] ; then
    rev=$(echo "$rev"|sed -e "s/.*://")
    rev="/rev/$rev";
fi
echo "$url$rev" | sed -e "s@//rev@/rev@"
# vi:set syntax=sh
